name: Java CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          
  upload_files:
    runs-on: ubuntu-latest
    env: 
     target_sshid: ${{secrets.TIMEGATE_SSH_USR}}
     target_sshpwd: ${{secrets.TIMEGATE_SSH_PWD}}
    needs: build
    name: Upload a builded file.
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: Package
        path: staging   
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: staging
    - name: filecheck
      run: pwd && ls -al
    - name: user/pwd check
      run: echo ${target_sshid} / ${target_sshpwd}
    # - name: Upload Files
    #   id: upload
      # uses: Creepios/sftp-action@v1.0.3
      # with:
      #   host: '127.0.0.1'
      #   port: 22
      #   username: 'root'
      #   password: 'password'
      #   localPath: './target/*.jar'
      #   remotePath: './'
